<?php

/**
    * Intergrates Flex Book web pages
    *
*/
function flex_book_node_view($node, $view_mode ) {
        if($node->type == 'flex_book'){
                $load_js = $node->field_load_js;//calls the field and makes it load.js
                    foreach($load_js['und'] as $js_file) // gets the und from laod.js
                      { drupal_add_js($js_file['value']); }// loads the JS to the page
                       
                      }
}